//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinXe
    {
        public int id { get; set; }
        public string ten { get; set; }
        public Nullable<double> gia { get; set; }
        public string mau_sac { get; set; }
        public string thong_so_ky_thuat { get; set; }
        public Nullable<int> danhmucid { get; set; }
        public string hinh { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
